* py-isort.el

[[https://travis-ci.org/paetzke/py-isort.el][https://travis-ci.org/paetzke/py-isort.el.svg?branch=master]]

Provides the =py-isort= command, which uses the external =isort= tool to tidy up the imports in the current buffer.

Install =isort= and download =py-isort=

#+BEGIN_SRC bash
$ pip install isort
$ wget https://raw.githubusercontent.com/paetzke/py-isort.el/master/py-isort.el \
       -O /your/path/py-isort.el
#+END_SRC

You can also install =py-isort= with /MELPA/:

#+BEGIN_SRC lisp
M-x package-install RET
py-isort RET
#+END_SRC

Add the =before-save-hook= to your =~/.emacs=

#+BEGIN_SRC lisp
(add-to-list 'load-path "/your/path/")
(require 'py-isort)
(add-hook 'before-save-hook 'py-isort-before-save)
#+END_SRC

Now every time you save your Python file =isort= will be executed on the current buffer.

To customize the behaviour of =isort= you can set the =py-isort-options= e.g.

#+BEGIN_SRC lisp
(setq py-isort-options '("--lines=100"))
#+END_SRC

You can also sort a region in the buffer by using =py-isort-region=.

#+BEGIN_SRC lisp
M-x py-isort-region RET
#+END_SRC

** CREDITS

Thanks to:

- Fredrik Bergroth
- Steve Purcell
- Syohei Yoshida
- Tristan Seligmann
- Jonathan Chu
- Laszlo Szathmary <jabbalaci>

** CHANGELOG

*** 0.7
- Add =py-isort-region= to sort the region in the buffer.

*** 0.6
- By passing the path of current buffer to isort (--setting-path), isort searches for configuration files in that path.

*** 0.5
- Fixed typo.

*** 0.4
- Replaced incf and decf.

*** 0.3
- Added check if isort executable is present.

*** 0.2
- Added options to change =isort='s behaviour.



Copyright (C) 2014, Friedrich Paetzke (paetzke@fastmail.fm). All rights reserved.
